version: '2'
networks:
  app-net:
    ipam:
      config:
        - subnet: 192.168.65.0/24
services: 
  backend:
    container_name: back
    build: 
      context: ./backend/src/backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      app-net:
        ipv4_address: 192.168.65.5
  frontend:
    container_name: front
    build: 
      context: ./frontend/src/frontend
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8000:8000"
    networks:
      app-net:
        ipv4_address: 192.168.65.6
